-- ============================================================
-- SCHEMA: rpt
-- TABLE:  rpt.savings_recommendation
-- Desc:   Output from the savings recommendation engine.
--         Populated by SavingsService — NOT from user input.
--         Each run creates a new snapshot; history is preserved.
-- ============================================================

CREATE TABLE IF NOT EXISTS rpt.savings_recommendation (
    id                     BIGSERIAL       PRIMARY KEY,
    member_id              BIGINT          NOT NULL,
    total_income           NUMERIC(10,2),
    total_expenses         NUMERIC(10,2),
    current_savings_rate   NUMERIC(5,2),
    top_category_1         VARCHAR(50),
    top_category_1_amount  NUMERIC(10,2),
    top_category_2         VARCHAR(50),
    top_category_2_amount  NUMERIC(10,2),
    top_category_3         VARCHAR(50),
    top_category_3_amount  NUMERIC(10,2),
    recommendation_text    TEXT,
    generated_at           TIMESTAMP       DEFAULT NOW(),

    CONSTRAINT fk_rpt_savings_rec_member
        FOREIGN KEY (member_id) REFERENCES ods.member(id)
);

COMMENT ON TABLE rpt.savings_recommendation IS 'Savings recommendation snapshots — generated by business logic';
